### ISSUE TITLE
Adjust the hyperlinks to open in separate tabs 

### ISSUE THREAD

**Issue by blikyar99** [global-input/global-input-web#10]
Can we make the hyperlinks to open in a different tab rather than open on top of the current page?  Because when I clicked the hyperlink it goes directly to github and I need to click return button to come back to Global input App page. Highlighted below: 
![image](https://user-images.githubusercontent.com/40795593/42219817-737f3092-7ecd-11e8-91db-d11f928fc8c6.png)

**Comment by dhewzulla** [comment]
ok, make sense to open the page for external link on new tab. I will do that:
https://growth.org/discuss/external-links-open-them-in-a-new-tab-or-in-the-same-tab-why-any-data
