### ISSUE TITLE
Update the blue texts and format them to make it consistent 

### ISSUE THREAD

**Issue by blikyar99** [global-input/global-input-web#11]
We need to update all the blue texts as the first one, but need to adjust the size of the text as well as the format. We need to be consistent on all other blue texts followed in the below sections. 
![image](https://user-images.githubusercontent.com/40795593/42219941-c611fd94-7ecd-11e8-9230-dfc0f7e95ca9.png)

**Comment by dhewzulla** [comment]
Need to separate the text on top of the image from the image and use normal HTML text.
will do together with the task that update the big blue text

**Comment by dhewzulla** [comment]
@blikyar99  done it as you said, how about on the mobile screen?

**Comment by blikyar99** [comment]
@dhewzulla it works perfectly. All images are centered and looks good now
