### ISSUE TITLE
correcting a word in About's section 

### ISSUE THREAD

**Issue by blikyar99** [global-input/global-input-web#12]
Let’s try to avoid repeating a word in the same sentence. Let’s take it: Global input App is a free application, …….   
![image](https://user-images.githubusercontent.com/40795593/42223567-58cd0494-7ed8-11e8-8bcb-5f095c3f2400.png)

**Comment by dhewzulla** [comment]
"Global Input App" is the name of the app. Maybe in the future we should rebranding not to use "App" in the name of the app.  The difference between app and application is debatable issue, so I tended not to call Global Input App as "application"

**Comment by blikyar99** [comment]
@dhewzulla  Ok agreed.
