### ISSUE TITLE
The main page is broken when opened with IE 

### ISSUE THREAD

**Issue by blikyar99** [global-input/global-input-web#16]
I have opened the web page on Internet Explorer and the page doesn't appears correct: 
![image](https://user-images.githubusercontent.com/40795593/42318076-435671b4-804e-11e8-9b0e-a8286ce015b6.png)

**Comment by dhewzulla** [comment]
could you confirm it is edge or ie

**Comment by dhewzulla** [comment]
if it is fine with edge, only broken with ie. Do we need to support something even MS doesn't?
