### ISSUE TITLE
The top of the website shows a frame as such (Highlighted in blue), we need to fix

### ISSUE THREAD

**Issue by dhewzulla** [global-input/global-input-web#7]
The top of the website shows a frame as such (Highlighted in blue), we need to fix this:

![screenshot 2018-07-03 12 58 11](https://user-images.githubusercontent.com/8720850/42218511-c3f88da0-7ec0-11e8-8a18-c42ec8d27caa.png)

**Comment by dhewzulla** [comment]
Is it possible to let me know which browser you are using, for I am struggling to to make that scroll bar appear on my side so that I can verify the fix?
1. I will make the overflowed the text to be hidden so that changing text content with different length will not affect other parts of the page
2. Make sure to make the text fit to that cell by controlling the length of the text

**Comment by dhewzulla** [comment]
@blikyar99 could you let me know which browser showed that frame?

**Comment by blikyar99** [comment]
@dhewzulla I'm using Chrome. version 67.0.3396.99   reloaded the main page several time and it's still shows that frame.

**Comment by dhewzulla** [comment]
@blikyar99 I have made the changes, but I could not tested it on my side for some reason.
Could you test the following website to see whether the issue is fixed?
https://udinput.co.uk/
You may need to refresh the page.

**Comment by blikyar99** [comment]
@dhewzulla Yes now it perfectly works on chrome and IE  we can  close this issue

**Comment by dhewzulla** [comment]
Brilliant! closing it now
