### ISSUE TITLE
Change the position of the image and align all images below

### ISSUE THREAD

**Issue by blikyar99** [global-input/global-input-web#8]
Let’s change the position of the image to the middle of the blank space on the right, or to the far right, to make the position of the image consistent in each section below.   (I saw you make it consistent in a way that first on the right, below is left and then right and then left….  But we have some blank space left, not sure if we make it all in the middle would looks better?)

![image](https://user-images.githubusercontent.com/40795593/42219684-0c522bc2-7ecd-11e8-9629-5fe99e810851.png)

**Comment by dhewzulla** [comment]
@blikyar99 
I have done the first-cell:"Second Screen Input & Control".
If you look at 
https://udinput.co.uk/
only the first section, ignoring the rest. If you are happy with that, then I can apply the same format to the rest.

**Comment by dhewzulla** [comment]
If you test both for mobile screen and desktop

**Comment by blikyar99** [comment]
@dhewzulla I think the image part looks good now, the position and the text above the image all fine. But i would keep the blue text on the left (subject part) as before. like the one in the second box below.  I think that looks visually comfortable, what do you think?
